
databases:
  - name: smiley_DB
    databaseName: smiley_DB
    user: smiley
    region: singapore

services:
  - type: web
    name: smiley
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smiley_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false